export const SURVEY_ID = "2026-ms";
export const API = "https://iaatvn44bj.execute-api.us-east-1.amazonaws.com";

export const SLIDES = [
  {
    id: "title",
    type: "title",
  },
  {
    id: "q1",
    type: "single",
    number: 1,
    question: "Hey... How are you feeling today?",
    options: [
      { key: "A", label: "Eagle" },
      { key: "B", label: "Birdie" },
      { key: "C", label: "Par" },
      { key: "D", label: "Bogey" },
      { key: "E", label: "Double Bogey" },
    ],
  },
  {
    id: "t_slay",
    type: "transition",
    text: "Slay Queen...",
    sub: "Glad to hear it. Let's ride.",
    show: (a) => a.q1 === "A" || a.q1 === "B",
  },
  {
    id: "t_beer",
    type: "transition",
    text: "Let's grab a dog\nand a beer at the turn.",
    sub: "We've all been there.",
    show: (a) => a.q1 === "D" || a.q1 === "E",
  },
  {
    id: "q2",
    type: "zip",
    number: 2,
    question: "What is your zip code?",
  },
  {
    id: "weather",
    type: "weather",
  },
  {
    id: "q3",
    type: "single",
    number: 3,
    question: "How are you feeling about your golf game right now?",
    options: [
      { key: "A", label: "Dialed in — don't change a thing" },
      { key: "B", label: "Pretty good, a few things to work on" },
      { key: "C", label: "It's a work in progress" },
      { key: "D", label: "I'm in a full rebuild" },
      { key: "E", label: "I've accepted who I am" },
    ],
  },
  {
    id: "q4_1",
    type: "number",
    number: "4a",
    question: "How many events have you played in so far this year?",
    min: 0,
    max: 8,
  },
  {
    id: "q4_2",
    type: "number",
    number: "4b",
    questionParts: [
      { text: "How many events " },
      { text: "did you want to", highlight: true },
      { text: " play in?" },
    ],
    min: 0,
    max: 8,
  },
  {
    id: "q4_3",
    type: "multi",
    number: "4c",
    question: "When you've had to miss an event, what was the most common reason?",
    hint: "Select all that apply",
    options: [
      { key: "A", label: "Family or personal commitment" },
      { key: "B", label: "Work schedule" },
      { key: "C", label: "Cost of the round" },
      { key: "D", label: "Course or location didn't appeal to me" },
      { key: "E", label: "Playing golf elsewhere that day" },
      { key: "F", label: "Not enough notice" },
      { key: "G", label: "I haven't missed many events" },
      { key: "H", label: "Other", hasText: true },
    ],
  },
  {
    id: "q6",
    type: "single",
    number: 5,
    question: "What's the most you're comfortable spending per round for a group event (greens fees only)?",
    options: [
      { key: "A", label: "Under $50" },
      { key: "B", label: "$50–$80" },
      { key: "C", label: "$80–$120" },
      { key: "D", label: "$120–$175" },
      { key: "E", label: "$175+ if the course is worth it" },
    ],
  },
  {
    id: "q7",
    type: "rating",
    number: 6,
    question: "Do you care about playing a nicer course, or would you rather play a goat track with your best buds?",
    leftLabel: "Give me the Delcastle\nand some beers",
    rightLabel: "Merion\nor GTFO",
  },
  {
    id: "q9",
    type: "single",
    number: 7,
    question: "Are you currently involved in any other regular golf commitments?",
    hint: "Leagues, standing tee times, other groups",
    options: [
      { key: "A", label: "Yes, and they sometimes conflict with our events" },
      { key: "B", label: "Yes, but they rarely conflict" },
      { key: "C", label: "No other regular commitments" },
    ],
  },
  {
    id: "q10",
    type: "single",
    number: 8,
    question: "If you were a cartoon character on the golf course, which would you be?",
    options: [
      { key: "A", label: "Inspector Gadget — lots of equipment, rarely works as intended" },
      { key: "B", label: "Darkwing Duck — dramatic entrance, questionable follow-through" },
      { key: "C", label: "Ren & Stimpy — one of you is way too intense, the other doesn't care at all" },
      { key: "D", label: "Johnny Bravo — looks great in the outfit, that's about it" },
      { key: "E", label: "Rocko — just trying to get through the round without a meltdown" },
    ],
  },
  {
    id: "q11",
    type: "rating",
    number: 9,
    question: "Would you be down for an EP road trip?",
    leftLabel: "Nah, that\nwouldn't be fun",
    rightLabel: "Hell yeah,\nbrother!",
  },
  {
    id: "q12",
    type: "text",
    number: 10,
    question: "Is there anything about how we run events that you'd change?",
    hint: "Even small things count. Optional.",
    optional: true,
  },
  {
    id: "q13",
    type: "text",
    number: 11,
    question: "Anything else you want us to know?",
    hint: "Optional.",
    optional: true,
  },
  {
    id: "done",
    type: "done",
  },
];

export const TOTAL_QUESTIONS = 11;
